// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAGxeQnL-tdOa2tNdl1R2PGx2gBpUe4o4',
    appId: '1:613604818952:web:691142156896735b5c11bd',
    messagingSenderId: '613604818952',
    projectId: 'community-app-32d31',
    authDomain: 'community-app-32d31.firebaseapp.com',
    storageBucket: 'community-app-32d31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMu-LBevu7XqgLCyZEyh8Fe8mZhHjGTGg',
    appId: '1:613604818952:android:474761c4e297922a5c11bd',
    messagingSenderId: '613604818952',
    projectId: 'community-app-32d31',
    storageBucket: 'community-app-32d31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHEoCYYyuk8HmqkKY-2W6L9YllAvilaOg',
    appId: '1:613604818952:ios:ad5987af8f6824e15c11bd',
    messagingSenderId: '613604818952',
    projectId: 'community-app-32d31',
    storageBucket: 'community-app-32d31.appspot.com',
    iosBundleId: 'com.example.communityAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHEoCYYyuk8HmqkKY-2W6L9YllAvilaOg',
    appId: '1:613604818952:ios:4beb6cc232776bc35c11bd',
    messagingSenderId: '613604818952',
    projectId: 'community-app-32d31',
    storageBucket: 'community-app-32d31.appspot.com',
    iosBundleId: 'com.example.communityAppUi.RunnerTests',
  );
}
